In [2]:
import numpy as np
a = np.array([[1,2,3],[22,33,1],[12,11,12]])
x = np.cov(a)
print(x)

[[  1.         -10.5          0.        ]
 [-10.5        264.33333333  -7.16666667]
 [  0.          -7.16666667   0.33333333]]


In [3]:
x = np.array([[1,2,3],[22,33,1],[12,11,12]])
a = x.T
a

array([[ 1, 22, 12],
       [ 2, 33, 11],
       [ 3,  1, 12]])